OneMits/Controllers/AdminPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OneMits.Data;
using OneMits.Models.AdminPanel;


namespace OneMits.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminPanelController : Controller
    {
        private readonly ICategory _categoryImplementation;
        private readonly IApplicationUser _applicationUserImplementation;
        private readonly IQuestion _questionImplementation;
        private readonly ApplicationDbContext _context;
        public AdminPanelController(ApplicationDbContext context, ICategory categoryImplementation, IApplicationUser applicationUserImplementation, IQuestion questionImplementation)
        {
            _categoryImplementation = categoryImplementation;
            _applicationUserImplementation = applicationUserImplementation;
            _questionImplementation = questionImplementation;
            _context = context;
        }
        public IActionResult Index()
        {
            int SumQuestions = 0;
            //int SumAnswers = 0;
            var Categories = _categoryImplementation.GetAll();
            foreach (var category in Categories)
            {
                SumQuestions += category.Questions.Count();
            }
            //foreach (var category in Categories)
            //{
            //    var Questions = category.Questions;
            //    foreach (var question in Questions)
            //    {
            //        SumAnswers += question.Answers.Count();
            //    }
            //}

            var model = new PanelIndexModel
            {
                NumberForums = _categoryImplementation.GetAll().Count(),
                NumberQuestions = SumQuestions,
                NumberMember = _applicationUserImplementation.GetAll().Count(),
                NumberUser = _context.Visits.Count(),
                NumberReplies = _questionImplementation.GetAllAnswers().Count(),
                //NumberLike = _categoryImplementation.GetAll().Count(),
            };

            return View(model);
        }

    }
}

OneMits/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OneMits.Data;
using OneMits.Data.Models;
using OneMits.Models.ApplicationUser;
using OneMits.Models.Category;
using OneMits.Models.Question;
using OneMits.Models.Search;

namespace OneMits.Controllers
{
    public class SearchController : Controller
    {
        private readonly IQuestion _questionImplementation;
        private readonly IApplicationUser _userImplementation;

        private IEnumerable<QuestionListingModel> postListings;
        private IEnumerable<ProfileModel> userListings;

        public SearchController(IQuestion questionImplementation, IApplicationUser userImplementation)
        {
            _questionImplementation = questionImplementation;
            _userImplementation = userImplementation;
        }


        public IActionResult UserResult(string searchQuery)
        {
            var userList = _userImplementation.GetSearchUserName(searchQuery);
            var areNoResults = (!string.IsNullOrEmpty(searchQuery) && !userList.Any());

            var profileModel = userList
                .Select(info => new ProfileModel
                {
                    UserId = info.Id,
                    Email = info.Email,
                    UserName = info.UserName,
                    UserRating = info.Rating,
                    MemberSince = info.MemberSince,
                    IsActive = info.IsActive,
                });
            var model = new SearchModel
            {
                UserList = profileModel,
                SearchQuery = searchQuery,
                EmptySearchResults = areNoResults
            };
            return View(model);
        }
        public IActionResult Result(string searchQuery)
        {
            var questions = _questionImplementation.GetFilteredQuestions(searchQuery);
            var areNoResults = (!string.IsNullOrEmpty(searchQuery) && !questions.Any());

            var questionListingModel = questions.Select(question => new QuestionListingModel
            {
                QuestionId = question.QuestionId,
                QuestionTitle = question.QuestionTitle,
                AuthorName = question.User.UserName,
                QuestionCreated = question.QuestionCreated.ToString(),
                AnswerCount = question.Answers.Count(),
                NumberView = question.NumberViews,
                Category = BuildForumListing(question)
            });
            var model = new SearchModel
            {
                Questions = questionListingModel,
                SearchQuery = searchQuery,
                EmptySearchResults = areNoResults
            };
            return View(model);
        }

        private CategoryListingModel BuildForumListing(Question question)
        {
            var catogory = question.Category;
            return new CategoryListingModel
            {
                CategoryId = catogory.CategoryId,
                CategoryTitle = catogory.CategoryTitle,
                CategoryImageUrl = catogory.CategoryImageUrl,
                CategoryDescription = catogory.CategoryDescription
            };

        }


        [HttpPost]
        public IActionResult Search(string searchQuery)
        {
            return RedirectToAction("Result", new { searchQuery });
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult UserList(string searchQuery)
        {
            return RedirectToAction("UserResult", new { searchQuery });
        }

    }
}

OneMits/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<OneMits.Data.Models.ApplicationUser> SignInManager
@inject UserManager<OneMits.Data.Models.ApplicationUser> UserManager

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] OneMits</title>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
        <script src="js/main.js"></script>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
        <link href="load-more-button.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" />
        <link rel="stylesheet" href="https://daneden.github.io/animate.css/animate.min.css" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="load-more-button.js"></script>

        <script>
            function openCity(evt, cityName) {
                var i, x, tablinks;
                x = document.getElementsByClassName("city");
                for (i = 0; i < x.length; i++) {
                    x[i].style.display = "none";
                }
                tablinks = document.getElementsByClassName("tablink");
                for (i = 0; i < x.length; i++) {
                    tablinks[i].className = tablinks[i].className.replace(" w3-red", "");
                }
                document.getElementById(cityName).style.display = "block";
                evt.currentTarget.className += " w3-red";
            }
        </script>
        
    </environment>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="css/style.css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/style.css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>

</head>
<body>

    <!--header-->
    <header role="banner" class="">
        <div id="cd-logo">
            <h2>
                <a style="text-decoration: none;" asp-controller="Home" asp-action="Index" class="cl-white Site-name">
                One MITS
                </a>
            </h2>
        </div>

        <nav class="main-nav pt-40">
            <partial name="_LoginPartial" />
        </nav>
    </header>


    <!--header end-->
    <!--NAVbar-->

    <div class="topnav" id="myTopnav">
        <a style="text-decoration: none;" asp-controller="Home" asp-action="Index">
        Home
        </a>
        <a style="text-decoration: none;" asp-controller="Category" asp-action="Index">
        Forums
        </a>
        @if (User.IsInRole("Admin"))
        {
            <a style="text-decoration: none;" asp-controller="AdminPanel" asp-action="Index">Admin Panel</a>
        }
        <a style="text-decoration: none;" asp-controller="Home" asp-action="AboutUs">About Us</a>
        <a style="float: right; padding: 0px 0px 0px 0px;">
            <form class="Search-bar example" asp-controller="Search" asp-action="Search" method="post">
                <input name="SearchQuery" type="text" placeholder="Search.." required/>
            </form>
        </a>

        <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
    </div>

    <!--NAvbar end-->

    @RenderBody()


    <footer>
        <div class="footer-end mt-50">
            <div class="container">
                Copyright By - OneMITS
            </div><!--- END CONTAINER -->
        </div>
    </footer>


    
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>